apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-elde
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-elde
    app.kubernetes.io/part-of: tkrw-pr714-0075-0021-app
  name: devfile-sample-elde
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-elde
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-elde
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0021-tenant/tkrw-pr714-0075-0021-app/devfile-sample-elde@sha256:507fa108a5400fbe8e6092d9ffeeccfd821e6aec3772b345d698eb5d417fdbed
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
